{{- if .Values.cronJob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "whoop-scraper.fullname" . }}
  labels:
    {{- include "whoop-scraper.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  {{- if .Values.cronJob.timeZone }}
  timeZone: {{ .Values.cronJob.timeZone | quote }}
  {{- end }}
  suspend: {{ .Values.cronJob.suspend }}
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronJob.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "whoop-scraper.selectorLabels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "whoop-scraper.serviceAccountName" . }}
          restartPolicy: {{ .Values.cronJob.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: whoop-scraper
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- toYaml .Values.cronJob.args | nindent 16 }}
              env:
                {{- include "whoop-scraper.env" . | nindent 16 }}
              {{- if or .Values.secret.enabled .Values.envFrom }}
              envFrom:
                {{- if .Values.secret.enabled }}
                - secretRef:
                    name: {{ include "whoop-scraper.secretName" . }}
                {{- end }}
                {{- with .Values.envFrom }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              {{- end }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
